# Generated by Django 4.0.4 on 2022-09-05 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AddField(
            model_name='member',
            name='firstname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='lastname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='User', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_ordered',
            field=models.DateField(default=datetime.datetime(2022, 9, 5, 19, 21, 3, 399181)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 10, 19, 21, 3, 399181)),
        ),
    ]
