# Generated by Django 4.1.1 on 2022-09-26 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_member_username_member_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_ordered',
            field=models.DateField(default=datetime.datetime(2022, 9, 25, 22, 32, 16, 463572)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 30, 22, 32, 16, 463572)),
        ),
    ]
