# Generated by Django 4.1.1 on 2022-09-26 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_books_image_alter_orders_date_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_ordered',
            field=models.DateField(default=datetime.datetime(2022, 9, 25, 23, 51, 30, 134974)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 30, 23, 51, 30, 134974)),
        ),
    ]
